In [5]:
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv("./rovMatchData.csv")
data

,offTeamBlue,jungleTeamBlue,mageTeamBlue,carryTeamBlue,supTeamBlue,supTeamRed,carryTeamRed,mageTeamRed,jungleTeamRed,offTeamRed,result_Blue
0,Omen,Maloch,Liliana,Joker,Zip,Xeniel,Violet,Krixi,Yan,Yena,1
1,Florentio,Elandorr,Rouie,Capheny,Arum,Mortos,Tel'annas,Aya,Nakroth,Skud,1
2,Ryoma,Nakroth,Kahlii,Elsu,Toro,Helen,Slimz,Annette,Zuka,Riktor,1
3,Helen,Skud,Mganga,Violet,Mina,Zip,Celica,Tulen,Tachi,Omen,1
4,Ryoma,Zuka,Lorion,Capheny,Xeniel,Annette,Joker,Tulen,Nakroth,Riktor,1
5,Yena,Zill,Krixi,Lindis,Krizzix,Lumburr,Capheny,Liliana,Taara,Skud,1
6,Qi,Wonder Woman,Rouie,Violet,Chaugnar,Superman,Joker,Liliana,Tachi,Skud,1
7,Ryoma,Zuka,Mganga,Hayate,Thane,Toro,Elsu,Aya,Kriknak,Murad,1
8,Yena,Aoi,Yue,Lindis,Xeniel,Zip,Violet,Tulen,Yan,Riktor,1
9,Mina,Yan,Krixi,Celica,Helen,Omen,Wisp,Yue,Aoi,Lauriel,1
10,Yena,Taara,Krixi,Capheny,Helen,Rouie,Joker,Zata,Kriknak,Omen,1
11,Veres,Tachi,Tulen,Violet,Thane,Taara,Bright,Liliana,Zuka,Xeniel,1
12,Ryoma,Tulen,Rouie,Violet,Veres,Superman,Joker,Liliana,Wonder Woman,Florentino,1
13,Omen,Batman,Illumia,Violet,Thane,Murad,Valhein,Liliana,Zuka,Taara,1

In [23]:
data = pd.read_csv("./rovMatchData.csv")
newMatch = {'result_Blue' : 1}
for i in data.columns[:-1]:
    newMatch[i] = [input(f'{i} : ')]
display(pd.DataFrame(newMatch))
pd.concat([data, pd.DataFrame(newMatch)]).to_csv("rovMatchData.csv", index=False)
print("newMatch added")

,result_Blue,offTeamBlue,jungleTeamBlue,mageTeamBlue,carryTeamBlue,supTeamBlue,supTeamRed,carryTeamRed,mageTeamRed,jungleTeamRed,offTeamRed
0,1,Qi,Aoi,Yue,Valhein,Lumburr,Baldum,Violet,Liliana,Zuka,Veres

newMatch added